name: CI

on: push

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout latest lmdb submodule
      run: git submodule update --init --recursive
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container: swift:latest
    steps:
    - uses: actions/checkout@v1
    - name: Checkout latest lmdb submodule
      run: git submodule update --init --recursive
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
